name: Build nolusd

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "v[0-9]**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: nolusd-${{ matrix.targetos }}-${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.wasm
            !tests/**
            **/**.go !**/*_test.go
            go.mod
            go.sum
            Makefile
            .github/workflows/build.yml
      - name: 🐿 Setup Golang
        uses: actions/setup-go@v5
        if: env.GIT_DIFF
        with:
          go-version-file: go.mod
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
      - name: Download Dependencies
        if: env.GIT_DIFF
        run: go mod download
      - name: Build osmosisd
        if: env.GIT_DIFF
        run: |
          GOWRK=off go build cmd/nolusd/main.go
      - name: Upload nolusd artifact
        if: env.GIT_DIFF
        uses: actions/upload-artifact@v3
        with:
          name: nolusd-${{ matrix.targetos }}-${{ matrix.arch }}
          path: cmd/nolusd/nolusd
