name: Test
on:
  workflow_dispatch:

jobs:
  test-unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      
      - uses: actions/checkout@v3
      
      - run: |
          make test-unit
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results-out
          path: |
            cover.out
          retention-days: 1

  test-unit-coverage:
    name: Code coverage reports
    needs: test-unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/checkout@v3

      - name: Download coverage result
        uses: actions/download-artifact@v3
        with:
          name: coverage-results-out
      
      - run: |
          make test-unit-coverage
          make test-unit-coverage-report

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            coverage.xml
            coverage.html
