name: Test Fuzz
on:
  workflow_dispatch:

jobs:
  nondeterminism:
    name: Test App State Determinism
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      
      - uses: actions/checkout@v3

      - run: |
          make test-sim-nondeterminism

  import-export:
    name: Test App Import Export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/checkout@v3
      
      - run: |
          make test-sim-import-export
